#! /usr/bin/env sh

REPOS_DIR="${REPOS_DIR:-${HOME}/Repos}"
selected="${1:-}"

if [ ! -d "${REPOS_DIR:-}" ]; then
    REPOS_DIR='.'
fi

selected=$(find "${REPOS_DIR}" -type d -mindepth 1 -maxdepth 4 -exec test -d {}/.git \; -print -prune | fzf --query "${selected}" --select-1)

if [ -z "${selected:-}" ]; then
    exit 0
fi

(
    cd "${selected}"
    url=$(git remote get-url upstream 2>/dev/null)

    if [ -z "${url:-}" ]; then
        url=$(git remote get-url origin 2>/dev/null)
    fi

    if [ -z "${url:-}" ]; then
        printf 'error: no url found for git repository\n'
        exit 1
    fi

    open "${url:-}"
)
