#! /usr/bin/env sh

REPOS_DIR="${REPOS_DIR:-${HOME}/Repos}"
selected="${1:-}"

if [ ! -d "${REPOS_DIR:-}" ]; then
	REPOS_DIR='.'
fi

selected=$(find "${REPOS_DIR}" -type d -mindepth 1 -maxdepth 4 -exec test -d {}/.git \; -print -prune | fzf --query "${selected}" --select-1)

if [ -z "${selected:-}" ]; then
	exit 0
fi

name=$(basename "${selected}" | tr . _)

if ! tmux has-session -t "${name}" 2>/dev/null; then
	tmux new-session -ds "${name}" -c "${selected}"
fi

tmux attach-session -t "${name}" -c "${selected}"
