#! /usr/bin/env sh

now=$(date +'%Y-%M-%d-%H%M%S')
backup_path="backup/${now}"

mkdir -p "${backup_path}" 1>/dev/null 2>&1 || true

__backup() {
	name="${1:-}"

	if [ -z "${name:-}" ]; then
		return 0
	fi

	path="${HOME}/${name}"

	if [ -f "${path:-}" ] && [ ! -h "${path:-}" ]; then
		printf 'backing up %s to %s\n' "${name}" "${backup_path}"
		mv "${path}" "${backup_path}"
	fi
}

__backup .config
__backup .zshrc
