#! /usr/bin/env sh

INSTALL_DIR="$(cd -- "$(dirname -- "$0")" && pwd -P)"

# ensure that brew is installed
if ! command -v brew 1>/dev/null 2>&1 && [ ! -x "/opt/homebrew/bin/brew" ]; then
	# install brew
	/bin/bash -c "CI=true $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh) && brew config"
fi

brew_cmd=$(command -v brew 2>&1)

if [ -z "${brew_cmd:-}" ]; then
	brew_cmd=/opt/homebrew/bin/brew
fi

if [ ! -x "${brew_cmd:-}" ]; then
	printf '\n\nBREW COULD NOT BE FOUND\n\n' >&2
	exit 1
fi

eval "$(${brew_cmd} shellenv)"

brew update
brew install \
	jandedobbeleer/oh-my-posh/oh-my-posh \
	curl \
	fzf \
	git \
	git-town \
	gh \
	go \
	nvim \
	ripgrep \
	stow \
	tmux \
	zinit \
	zsh

brew install --cask \
	font-meslo-lg-nerd-font \
	font-fira-code-nerd-font

brew tap homebrew/command-not-found

# THEME_DIR="${INSTALL_DIR}/.config/alacritty/themes"

# THEME=${THEME:-catppuccin_mocha}
# THEME_FILE="${THEME}.toml"

# THEME_URL="https://raw.githubusercontent.com/alacritty/alacritty-theme/master/themes/${THEME_FILE}"
# THEME_OUT="${THEME_DIR}/${THEME_FILE}"

# mkdir -p "${THEME_DIR}"
# curl --silent "${THEME_URL}" --output "${THEME_OUT}"

stow --dir="${INSTALL_DIR}" --target="${HOME}" .

ZSH_BIN="$(command -v zsh)"

if [ "${ZSH_BIN:-}" != "${SHELL:-}" ]; then
	chsh -s "${ZSH_BIN}"
fi
