#! /usr/bin/env sh

REPOS_DIR="${REPOS_DIR:-${HOME}/Repos}"
selected="${1:-}"

if [ ! -d "${REPOS_DIR:-}" ]; then
	REPOS_DIR='.'
fi

if [ "${selected:-}" = "." ]; then
	REPOS_DIR="${PWD}"
	selected=
fi

selected=$(find "${REPOS_DIR}" -type d -mindepth 0 -maxdepth 4 -exec test -d {}/.git \; -print -prune | fzf --query "${selected}" --select-1)

if [ -z "${selected:-}" ]; then
	exit 0
fi

name=$(basename "${selected}" | tr . _)

if ! tmux has-session -t "${name}" 2>/dev/null; then
	tmux -u new-session -d -s "${name}" -c "${selected}" -x - -y - \; \
		split-window -v -b -l '90%' -c "${selected}" "${EDITOR} ." \; \
		new-window -a -d -c "${selected}"
fi

tmux -u attach-session -t "${name}" -c "${selected}"
