#!/usr/bin/env sh

plugin_dir="$(readlink -fn ${HOME}/.config/sketchybar/plugins)"


if [ ! -d "${plugin_dir:-}" ]; then
	printf 'error: plugin dir (%s) does not exist\n\n'
	exit 1
fi

# (
# 	tmp="$(mktemp)"
# 	cd "${plugin_dir}"
# 	curl -fslo "${tmp}" \
# 		https://github.com/kvndrsslr/sketchybar-app-font/releases/download/latest/icon_map.sh
# 	git diff icon_map.sh "${tmp}"
# )

read -p "Are you sure you want to apply? [y/N]" response
response="${response:1}"
if [ "${response:-}" =~ ^(y| )]; then
	echo yes
	# mv "${tmp}" icon_map.sh
	# chmod +x icon_map.sh
	# sketchybar --reload
fi
echo no
