[font]
size = 18

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Light"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Semibold"
