import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml",
    "~/.config/alacritty/fonts/firacode_nerd_font_mono.toml",
]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
option_as_alt = "Both"
startup_mode = "SimpleFullScreen"

[window.padding]
x = 10
y = 0

[window.dimensions]
columns = 160
lines = 40
