#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[palette]
blue = '#8AADF4'
lavender = '#B7BDF8'
os = '#ACB0BE'
pink = '#F5BDE6'
red = '#ef5350'
text = '#494D64'
white = '#FFFFFF'

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
type = 'os'
style = 'diamond'
leading_diamond = '╭─'
template = '{{.Icon}}'
background = 'blue'
foreground = 'black'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'session'
style = 'diamond'
trailing_diamond = ''
template = ' {{ .UserName }} '
background = 'blue'
foreground = 'black'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'path'
style = 'powerline'
powerline_symbol = ''
template = '  {{ .Path }} '
background = 'p:pink'
foreground = 'p:text'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
folder_icon = '  '
home_icon = ''
style = 'folder'

[[blocks.segments]]
type = 'git'
style = 'diamond'
leading_diamond = '<transparent></>'
trailing_diamond = ''
# background_templates = [
#     '{{ if or (.Working.Changed) (.Staging.Changed) }}p:lavender{{ end }}',
#     '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:blue{{ end }}',
#     '{{ if gt .Ahead 0 }}p:pink{{ end }}',
#     '{{ if gt .Behind 0 }}p:red{{ end }}',
# ]
template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#ef5350>  {{ .Staging.String }}</>{{ end }} '
background = 'p:lavender'
foreground = 'p:text'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
branch_icon = ' '
cherry_pick_icon = ' '
commit_icon = ' '
fetch_status = true
fetch_upstream_icon = false
merge_icon = ' '
no_commits_icon = ' '
rebase_icon = ' '
revert_icon = ' '
tag_icon = ' '

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
template = '╰─'
background = 'transparent'
foreground = 'blue'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'status'
style = 'plain'
foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
template = ' '
background = 'transparent'
foreground = 'p:text'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
always_enabled = true

[transient_prompt]
foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
]
background = 'transparent'
template = '❯ '

[secondary_prompt]
foreground = 'magenta'
background = 'transparent'
template = '❯❯ '
