#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[palettes]
template = "catppuccin-mocha"

[palettes.list.catppuccin-latte]
rosewater = '#dc8a78'
flamingo = '#dd7878'
pink = '#ea76cb'
mauve = '#8839ef'
red = '#d20f39'
maroon = '#e64553'
peach = '#fe640b'
yellow = '#df8e1d'
green = '#40a02b'
teal = '#179299'
sky = '#04a5e5'
sapphire = '#209fb5'
blue = '#1e66f5'
lavender = '#7287fd'
text = '#4c4f69'
subtext_1 = '#5c5f77'
subtest_0 = '#6c6f85'
overlay_2 = '#7c7f93'
overlay_1 = '#8c8fa1'
overlay_0 = '#9ca0b0'
surface_2 = '#acb0be'
surface_1 = '#bcc0cc'
surface_0 = '#ccd0da'
base = '#eff1f5'
mantle = '#e6e9ef'
crust = '#dce0e8'

[palettes.list.catppuccin-mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext_1 = '#bac2de'
subtest_0 = '#a6adc8'
overlay_2 = '#9399b2'
overlay_1 = '#7f849c'
overlay_0 = '#6c7086'
surface_2 = '#585b70'
surface_1 = '#45475a'
surface_0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
type = 'os'
style = 'diamond'
leading_diamond = '╭─'
template = '{{.Icon}}'
background = 'p:blue'
foreground = 'p:crust'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'session'
style = 'diamond'
trailing_diamond = ''
template = ' {{ .UserName }} '
background = 'p:blue'
foreground = 'p:crust'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'path'
style = 'diamond'
leading_diamond = '<p:crust></>'
trailing_diamond = ''
template = '  {{ .Path }} '
background = 'p:pink'
foreground = 'p:crust'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
folder_icon = '  '
home_icon = ''
style = 'folder'

[[blocks.segments]]
type = 'git'
style = 'diamond'
leading_diamond = '<p:crust></>'
trailing_diamond = ''
template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
background = 'p:green'
foreground = 'p:crust'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
branch_icon = ' '
cherry_pick_icon = ' '
commit_icon = ' '
fetch_status = true
fetch_upstream_icon = false
merge_icon = ' '
no_commits_icon = ' '
rebase_icon = ' '
revert_icon = ' '
tag_icon = ' '

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
template = '╰─'
background = 'transparent'
foreground = 'p:blue'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'status'
style = 'plain'
foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
template = ' '
background = 'transparent'
foreground = 'p:subtext_1'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
always_enabled = true

[transient_prompt]
foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:subtext_1{{end}}",
]
background = 'transparent'
template = '❯ '

[secondary_prompt]
foreground = 'p:red'
background = 'transparent'
template = '❯❯ '
